// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/domain/usecases/get_forecast_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/data/models/forecast_model.dart' as _i3;
import 'package:weather_app/domain/entities/weather_entity.dart' as _i2;
import 'package:weather_app/domain/repositories/weather_repository.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherEntity_0 extends _i1.SmartFake implements _i2.WeatherEntity {
  _FakeWeatherEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForecastModel_1 extends _i1.SmartFake implements _i3.ForecastModel {
  _FakeForecastModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i4.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeatherEntity> getWeatherByCity(
    String? city, {
    String? units = 'metric',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getWeatherByCity, [city], {#units: units}),
            returnValue: _i5.Future<_i2.WeatherEntity>.value(
              _FakeWeatherEntity_0(
                this,
                Invocation.method(#getWeatherByCity, [city], {#units: units}),
              ),
            ),
          )
          as _i5.Future<_i2.WeatherEntity>);

  @override
  _i5.Future<_i2.WeatherEntity> getWeatherByCoordinates(
    double? latitude,
    double? longitude, {
    String? units = 'metric',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getWeatherByCoordinates,
              [latitude, longitude],
              {#units: units},
            ),
            returnValue: _i5.Future<_i2.WeatherEntity>.value(
              _FakeWeatherEntity_0(
                this,
                Invocation.method(
                  #getWeatherByCoordinates,
                  [latitude, longitude],
                  {#units: units},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.WeatherEntity>);

  @override
  _i5.Future<_i3.ForecastModel> getForecastByCity(
    String? city, {
    String? units = 'metric',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getForecastByCity, [city], {#units: units}),
            returnValue: _i5.Future<_i3.ForecastModel>.value(
              _FakeForecastModel_1(
                this,
                Invocation.method(#getForecastByCity, [city], {#units: units}),
              ),
            ),
          )
          as _i5.Future<_i3.ForecastModel>);

  @override
  _i5.Future<_i3.ForecastModel> getForecastByCoordinates(
    double? latitude,
    double? longitude, {
    String? units = 'metric',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getForecastByCoordinates,
              [latitude, longitude],
              {#units: units},
            ),
            returnValue: _i5.Future<_i3.ForecastModel>.value(
              _FakeForecastModel_1(
                this,
                Invocation.method(
                  #getForecastByCoordinates,
                  [latitude, longitude],
                  {#units: units},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.ForecastModel>);
}
